### ISSUE TITLE
Window not defined

### ISSUE THREAD

**Issue by ICEPrey** [M2G/react-plyr#9]
ReferenceError: window is not defined
    at Object.<anonymous> (C:\Users\abuws\Desktop\Aniorb\Aniorb Beta\aniorb\node_modules\@m2g\react-plyr\build\react-plyr.js:2:315)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.@m2g/react-plyr (C:\Users\abuws\Desktop\Aniorb\Aniorb Beta\aniorb\.next\server\pages\watching\[...slug].js:4669:18)
    at __webpack_require__ (C:\Users\abuws\Desktop\Aniorb\Aniorb Beta\aniorb\.next\server\pages\watching\[...slug].js:23:31)
    at Module../components/watch/watchingContainer.js (C:\Users\abuws\Desktop\Aniorb\Aniorb Beta\aniorb\.next\server\pages\watching\[...slug].js:407:73)
    at __webpack_require__ (C:\Users\abuws\Desktop\Aniorb\Aniorb Beta\aniorb\.next\server\pages\watching\[...slug].js:23:31)
    at Module../pages/watching/[...slug].js (C:\Users\abuws\Desktop\Aniorb\Aniorb Beta\aniorb\.next\server\pages\watching\[...slug].js:4510:93)
    at __webpack_require__ (C:\Users\abuws\Desktop\Aniorb\Aniorb Beta\aniorb\.next\server\pages\watching\[...slug].js:23:31)
    at C:\Users\abuws\Desktop\Aniorb\Aniorb Beta\aniorb\.next\server\pages\watching\[...slug].js:91:18
    at Object.<anonymous> (C:\Users\abuws\Desktop\Aniorb\Aniorb Beta\aniorb\.next\server\pages\watching\[...slug].js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requirePage (C:\Users\abuws\Desktop\Aniorb\Aniorb Beta\aniorb\node_modules\next\dist\next-server\server\require.js:1:1184)

**Comment by M2G** [comment]
you use CRA ?? like the project (if you download the project, you get this error ?)

**Comment by ICEPrey** [comment]
No this is from the NPM

**Comment by M2G** [comment]
I tried with CRA (https://github.com/facebook/create-react-app), it works well, can you confirm this for me from your side ? thx

**Comment by ICEPrey** [comment]
I am so sorry the error was on my side

**Comment by ICEPrey** [comment]
It happens when I try to change the ratio like, ratio='16:9' or when I try width='1769' etc

**Comment by ICEPrey** [comment]
> I tried with CRA (https://github.com/facebook/create-react-app), it works well, can you confirm this for me from your side ? thx

also I am using NextJS

**Comment by ICEPrey** [comment]
https://user-images.githubusercontent.com/40725969/111082981-766b4800-84c8-11eb-8ffe-6028c7ef8877.mp4

**Comment by M2G** [comment]
I have never used NextJS, maybe try this : https://stackoverflow.com/questions/56319997/nextjs-window-is-not-defined 
please, come back to me to keep me informed. 
Matt

**Comment by ICEPrey** [comment]
That makes the video work, but then the resizing and ratio doesn't work. But anyways this is my own problem I'll try to solve sorry.

**Comment by M2G** [comment]
I checked the code source and the ratio is set to "16:9" by default. However, I think the ratio is only available for: "[...] embedded players (YouTube and Vimeo)" source: https://github.com/sampotts/plyr/issues/1099#issuecomment-404839007

**Comment by M2G** [comment]
I'll look into it myself, in meantime, thanks for your feedback

**Comment by ICEPrey** [comment]
> I checked the code source and the ratio is set to "16:9" by default. However, I think the ratio is only available for: "[...] embedded players (YouTube and Vimeo)" source: [sampotts/plyr#1099 (comment)](https://github.com/sampotts/plyr/issues/1099#issuecomment-404839007)

Ah alright, thank you
